#ifndef _x509acreq_h_
#define _x509acreq_h_

#include "cryptobase/x509ac.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define PEM_STRING_ATTRIBUTE_CERTIFICATE_REQUEST "ATTRIBUTE CERTIFICATE REQUEST"

typedef struct CRYPTOBASE_API X509AC_ISSUE_INFO_st
{
	ASN1_INTEGER *templateId;
	X509AC_HOLDER *holder;
	X509AC_ISSUER *issuer;
	X509AC_VAL *validity;
	STACK_OF(X509_ATTRIBUTE) *attributes;
	STACK_OF(X509_EXTENSION) *extensions;
} X509AC_ISSUE_INFO;

typedef struct CRYPTOBASE_API X509AC_SEARCH_INFO_st
{
	X509AC_HOLDER *holder;
	STACK_OF(ASN1_OBJECT) *attributesOid;
} X509AC_SEARCH_INFO;


typedef struct CRYPTOBASE_API X509AC_REV_INFO_st
{
	X509AC_HOLDER *holder;
	ASN1_OBJECT *attributeOid;
} X509AC_REV_INFO;

typedef struct CRYPTOBASE_API X509AC_REQ_st
{
	ASN1_INTEGER *version;
	ASN1_INTEGER *reqType;
	X509AC_ISSUE_INFO *issueInfo;
	X509AC_SEARCH_INFO *searchInfo;
	X509AC_REV_INFO *revInfo;
} X509AC_REQ;

DECLARE_ASN1_ITEM(X509AC_ISSUE_INFO)
DECLARE_ASN1_FUNCTIONS(X509AC_ISSUE_INFO)
DECLARE_ASN1_DUP_FUNCTION(X509AC_ISSUE_INFO)

DECLARE_ASN1_ITEM(X509AC_SEARCH_INFO)
DECLARE_ASN1_FUNCTIONS(X509AC_SEARCH_INFO)
DECLARE_ASN1_DUP_FUNCTION(X509AC_SEARCH_INFO)

DECLARE_ASN1_ITEM(X509AC_REV_INFO)
DECLARE_ASN1_FUNCTIONS(X509AC_REV_INFO)
DECLARE_ASN1_DUP_FUNCTION(X509AC_REV_INFO)

DECLARE_ASN1_ITEM(X509AC_REQ)
DECLARE_ASN1_FUNCTIONS(X509AC_REQ)
DECLARE_ASN1_DUP_FUNCTION(X509AC_REQ)
DECLARE_PEM_rw(X509AC_REQ, X509AC_REQ)


#ifdef __cplusplus
}
#endif

#endif // _x509acreq_h_
